### ISSUE TITLE
linux下编译不过啊，

### ISSUE THREAD

**Issue by QGB** [darkchii/C-libhttp#1]
$ gcc -I./  ./example/request_lib_example/example.cpp -o qgb
In file included from ./example/request_lib_example/example.cpp:2:
In file included from ./libhttp.hpp:3:
./libjson.hpp:2:10: fatal error: 'configure.h' file not found
#include "configure.h"
         ^~~~~~~~~~~~~
1 error generated.
$
$
$ vim libjson.hpp
$
$ gcc -I./  ./example/request_lib_example/example.cpp -o qgb
In file included from ./example/request_lib_example/example.cpp:2:
In file included from ./libhttp.hpp:3:
./libjson.hpp:3:10: fatal error: 'algo.h' file not found
#include "algo.h"
         ^~~~~~~~
1 error generated.
$ vim libjson.hpp

我把 "algo.h" "configure.h"  都改为  hpp，好了，被错误淹没

$
$
$ gcc -I./  ./example/request_lib_example/example.cpp -o qgb
In file included from ./example/request_lib_example/example.cpp:2:
./libhttp.hpp:75:21: error: unknown type name 'SOCKET'
                int build_connect(SOCKET & socket_fd, const char* host, unsigned short port)
                                  ^
./libhttp.hpp:100:66: error: use of undeclared identifier 'INVALID_SOCKET'
                        if ((socket_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_IP)) == INVALID_SOCKET)
                                                                                      ^
./example/request_lib_example/example.cpp:42:20: error: redefinition of 'headers'
        std::stringstream headers;
                          ^
./example/request_lib_example/example.cpp:24:20: note: previous definition is here
        std::stringstream headers;

**Comment by QGB** [comment]
忘了说，我的linux 是 termux。。

**Comment by darkchii** [comment]
抱歉啊，不怎么看github。关于linux下出错，我暂时没办法解决，因为身边没有linux的pc，开始虽然是在cente os下写得，后来换电脑，懒得折腾，就在windows上继续写了，所以没在linux上跑过，也没想到真的有人会用这个代码。。。我最近在忙着别的项目，等有空我会重新维护这个项目。谢谢你的issues，让我有了动力:)

**Comment by QGB** [comment]
@darkchii 我就是在手机上编译你这个代码的，我也觉得装linux太折腾了
